accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "accounts"

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
]

store/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include,re_path
from django.views.static import serve

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/$',views.TestPage.as_view(),name='test'),
    path('thanks/$',views.ThanksPage.as_view(),name='thanks'),

    re_path(r'^media/(?P<path>.*)$', serve,{'document_root':settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root':settings.STATIC_ROOT}), 
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):

    class Meta:
        fields = ('username','email','password1','password2')
        model = get_user_model()

        def __init__(self,*args,**kwargs):
            super().__init__(*args,**kwargs)
            self.fields['username'].label = 'Display Name'
            self.fields['email'].label = 'Email Address'

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from . import forms

# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

store/views.py
from django.views.generic import TemplateView


class HomePage(TemplateView):
    template_name = 'index.html'

    
class TestPage(TemplateView):
    template_name = 'test.html'  


class ThanksPage(TemplateView):
    template_name = 'thanks.html'      

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}



{% block content %}
    <div class="container">
        <h1>Login!</h1>
        <form method="POST">
            {% csrf_token %}
            {%bootstrap_form form %}
            <input type="submit" value="Login" class="btn btn-default">
        </form>
    </div>
{% endblock content %}
    

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}



{% block content %}
    <div class="container">
        <h1>Sign Up!</h1>
        <form method="POST">
            {% csrf_token %}
            {%bootstrap_form form %}
            <input type="submit" value="SignUp" class="btn btn-default">
        </form>
    </div>
{% endblock content %}
    

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Smart Store</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'store/css/master.css'%}">


  </head>


  <body>

    <nav class="navbar  mynav" role="navigation" id="navbar">
    			<div class="container">

            <a class="navbar-brand mynav" id="navbrand" href="{% url 'home' %}">Smart Store</a>

    					<ul class="navlist" id="navlist">
    						{% if user.is_authenticated %}
                      <li class="navitem"><a href="{% url 'accounts:logout' %}" class="link">Log out</a></li>
    						{% else %}
    						      <li class="navitem"><a href="{% url 'accounts:login' %}" class="link">Log in</a></li>
    						      <li class="navitem"><a href="{% url 'accounts:signup' %}" class="link">Sign up</a></li>
    						{% endif %}
    					</ul>



    			</div>
    		</nav>
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>



<canvas id="canvas"></canvas>



  </body>
  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to Smart Store!</h1>
    <h2>The best community for all things on outer space!</h2>
    <h2>Login or Sign-up for free to get started!</h2>


{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">

    <h1>You are now logged in!</h1>


    <h2 id="dashboard">YOUR DASHBOARD</h2>
  

  <div class="options">
    <div class="col">
      <button class="button" id="order-button">Your Orders</button>
      <button class="button" id="buy-button">Buy Again</button>
    </div>

    <div class="col">
      <button class="button" id="account-button">Your Account</button>
      <button class="button" id="list-button">Your Lists</button>
    </div>

  </div>

  <div class="sub">

    <h2>BROWSE MORE PRODUCTS</h2>
  </div>

  <div class="card-container">
    <div class="card">
      <img src="https://needline.in/wp-content/uploads/2020/09/brown-brad-min.jpg" alt="Product Image 1">
      <div class="card-content">
        <div class="product-title">BREAD</div>
        <div class="product-price">₹54</div>
        <button class="add-to-cart">Add to Cart</button>
      </div>
    </div>
  
    <div class="card">
      <img src="https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/71LuYzbvsPL.jpg" alt="Product Image 2">
      <div class="card-content">
        <div class="product-title">LAYS MAGIC MASALA</div>
        <div class="product-price">₹50</div>
        <button class="add-to-cart">Add to Cart</button>
      </div>
    </div>
  
    <div class="card">
      <img src="https://www.tradeindia.com/_next/image/?url=https%3A%2F%2Ftiimg.tistatic.com%2Ffp%2F1%2F007%2F790%2Fcrunchy-and-crispy-haldiram-punjabi-tadka-namkeen-packaging-type-packet-net-weight-45gram-459.jpg&w=750&q=75" alt="Product Image 3">
      <div class="card-content">
        <div class="product-title">HALDIRAM PUNJABI TADKA</div>
        <div class="product-price">₹80</div>
        <button class="add-to-cart">Add to Cart</button>
      </div>
    </div>
    <div class="card">
      <img src="https://5.imimg.com/data5/ANDROID/Default/2022/2/ZB/HX/DK/7349419/product-jpeg.jpg" alt="Product Image 3">
      <div class="card-content">
        <div class="product-title">MILK</div>
        <div class="product-price">₹27</div>
        <button class="add-to-cart">Add to Cart</button>
      </div>
    </div>
    <div class="card">
      <img src="https://www.jiomart.com/images/product/original/490000493/snickers-peanut-chocolate-45-g-product-images-o490000493-p490000493-0-202212052010.jpg?im=Resize=(420,420)" alt="Product Image 3">
      <div class="card-content">
        <div class="product-title">SNIKKERS CHOCOLATE BAR</div>
        <div class="product-price">₹35</div>
        <button class="add-to-cart">Add to Cart</button>
      </div>
    </div>
    <div class="card">
      <img src="https://www.quickpantry.in/cdn/shop/products/Tide_Detergent_1.5_kg_700x700.jpg?v=1603483780" alt="Product Image 3">
      <div class="card-content">
        <div class="product-title">DETERGENT</div>
        <div class="product-price">₹65</div>
        <button class="add-to-cart">Add to Cart</button>
      </div>
    </div>
  </div>

</div>




{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}